server:
  port: 8080
spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: root
#    password: 123456
    driver-class-name: org.h2.Driver
    data: classpath:/sql/init-data.sql
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace